-- Fix permissions for smart_user on smart_office_db
GRANT ALL ON SCHEMA public TO smart_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO smart_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO smart_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO smart_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO smart_user;
