# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_office_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=smart_user
spring.datasource.password=trytoguessit12345

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# JWT
app.jwt.secret=mySecretKeyForJWTTokenGenerationThatIsLongEnough2024OfficeSmart
app.jwt.expiration-ms=86400000

# Server
server.port=8080
